cmake_minimum_required(VERSION 3.31)
project(TessaveilAlphaRelink LANGUAGES CXX)
find_package(Qt6 6.8.3 EXACT REQUIRED COMPONENTS Widgets)
get_target_property(qt_kind Qt6::Core TYPE)
if(NOT qt_kind STREQUAL "STATIC_LIBRARY")
  message(FATAL_ERROR "Static Qt is required")
endif()
add_library(controller STATIC IMPORTED)
set_target_properties(controller PROPERTIES IMPORTED_LOCATION "${CMAKE_CURRENT_LIST_DIR}/../application/controller.a")
add_library(alpha_ui STATIC IMPORTED)
set_target_properties(alpha_ui PROPERTIES IMPORTED_LOCATION "${CMAKE_CURRENT_LIST_DIR}/../application/alpha_ui.a")
set_source_files_properties("../application/main.obj" PROPERTIES EXTERNAL_OBJECT TRUE GENERATED TRUE)
qt_add_executable(Tessaveil WIN32 ../application/main.obj)
set_target_properties(Tessaveil PROPERTIES LINKER_LANGUAGE CXX)
target_link_libraries(Tessaveil PRIVATE alpha_ui controller Qt6::Widgets bcrypt ntdll userenv ws2_32 dbghelp wtsapi32)
target_link_options(Tessaveil PRIVATE -static)
qt_import_plugins(Tessaveil INCLUDE Qt6::QWindowsIntegrationPlugin)
add_executable(qt_marker marker.cpp)
target_link_libraries(qt_marker PRIVATE Qt6::Core)
target_link_options(qt_marker PRIVATE -static)
