[package]
name = "tessaveil-core"
version = "0.1.0-alpha.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
argon2 = { version = "=0.5.3", default-features = false, features = ["zeroize"] }
chacha20poly1305 = "=0.10.1"
getrandom = "=0.2.16"
zeroize = { version = "=1.8.1", features = ["derive"] }
unicode-normalization = "=0.1.24"

[dev-dependencies]
tempfile = "=3.23.0"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "=0.61.2", features = ["Win32_Storage_FileSystem", "Win32_Foundation"] }
