"""Deterministic notices: preserved license texts plus exact bundled-list index."""

import argparse
from pathlib import Path

from tools.catalog.loader import load_catalog
from tools.catalog.validator import validate_catalog


def render(catalog):
    if any(f.severity == "error" for f in validate_catalog(catalog, require_terminal=True)):
        raise ValueError("invalid catalogue or unclosed bundled license decision")
    source = catalog.root / "docs/research/third-party-notices-source.txt"
    lines = ["Generated by python -m tools.notices; do not edit this output.",
             "License texts are preserved in docs/research/third-party-notices-source.txt.",
             "", source.read_text(encoding="utf-8").rstrip(), "",
             "Deterministic bundled dictionary index", "======================================", ""]
    for record in sorted(catalog.dictionaries, key=lambda r: r.id):
        d = record.data
        if record.wordlist_bytes is None:
            continue
        license = d["license"]
        if license["repository_redistribution"] != "allowed" or license["signpath_compatible"] != "compatible":
            raise ValueError("pending or nonpositive bundled license")
        lines.extend([f"Dictionary: {record.id}", f"File: {d['wordlist_path']}",
                      f"Source: {d['source']['url']}", f"Revision: {d['source']['revision']}",
                      f"SHA-256: {d['sha256']}", f"Count: {d['word_count']}",
                      f"License: {license['spdx_or_name']}", f"License source: {license['source_url']}",
                      f"Attribution: {license['attribution']}",
                      "Repository redistribution: allowed; SignPath compatibility: compatible (local assessment only)",
                      f"Decision evidence: {', '.join(sorted(license['decision_evidence']))}", ""])
    lines.extend(["Excluded dictionaries (no distributed word-list bytes)", "-----------------------------------------------------"])
    for record in sorted(catalog.dictionaries, key=lambda r: r.id):
        if record.wordlist_bytes is None:
            d = record.data
            lines.append(f"{record.id}: {d['status']}; redistribution={d['license']['repository_redistribution']}; "
                         f"SignPath={d['license']['signpath_compatible']}; NOT BUNDLED")
    return "\n".join(lines).rstrip() + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path.cwd()
    try:
        output = render(load_catalog(root)).encode("utf-8")
        path = root / "THIRD_PARTY_NOTICES"
        if args.check:
            if not path.is_file() or path.read_bytes() != output:
                raise ValueError("notices drift")
        else:
            path.write_bytes(output)
    except (OSError, ValueError):
        print("notices: FAIL (invalid inputs, pending bundled decision, or output drift)")
        return 1
    print("notices: PASS; all bundled dictionary decisions closed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
